### PR TITLE
add emacs-like key

### PR DESCRIPTION
**Pull request by skanehira**
Add emacs-like key for selecting autocomplete list

### CODE REVIEW

**Comment by aditya-K2** [comment]
@rivo I think we can expose a function for user like SelectNext or SelectPrevious so that the user can map the keys on his own end.

**Comment by aditya-K2** [comment]
any updates on this?

**Comment by rivo** [comment]
You can use [SetInputCapture](https://pkg.go.dev/github.com/rivo/tview#Box.SetInputCapture) to define your own key binds. I don't see why this PR is needed, especially because `tview` does not implement emacs-like key binds anywhere else.

**Comment by aditya-K2** [comment]
> You can use [SetInputCapture](https://pkg.go.dev/github.com/rivo/tview#Box.SetInputCapture) to define your own key binds. I don't see why this PR is needed, especially because `tview` does not implement emacs-like key binds anywhere else.

`SetInputCapture` captures the input for the `input field` and not the autocomplete menu. How can one access Autocomplete's Input?

**Pull request closed without merging**
