### PR TITLE
Add support for horizontal scrolling to List

### LINKED ISSUE #512: Horizonal scroll for List
I want to add horizonal scrolling to the list element, because for wide tables not everything could fit the screen.

image

There is no setting for this on the List element https://pkg.go.dev/github.com/rivo/tview#List

What is the proper way to do this? An example in wiki would be nice to have.

### PR DESCRIPTION
**Pull request by tslocum**
Resolves #512.

This change is available in [cview](https://gitlab.com/tslocum/cview), a fork of tview.

### CODE REVIEW

**Comment by abitrolly** [comment]
Is there an indicator that a column is scrolled?

**Comment by tslocum** [comment]
No horizontal indicator is drawn.  I [suggested changes](https://github.com/rivo/tview/pull/396) adding vertical scroll indicators in January, which could be adapted for this.

**Comment by abitrolly** [comment]
@tslocum maybe it is possible to modify List to be easier extendable to add these features in custom UI rather than patching and maintaining custom version of `tview`?

**Comment by tslocum** [comment]
Please see [this document](https://gitlab.com/tslocum/cview/blob/master/FORK.md) for an explanation of why I forked tview and the differences between the two.

**Comment by rivo** [comment]
@tslocum Just curious, have you tried this with multi-rune Unicode characters or even with characters that occupy more than one cell?

**Comment by rivo** [comment]
Well, the proper solution took me a few hours to figure out. It's not as easy as it may have seen because, as in many other places,

```
byte ≠ rune ≠ Unicode character
```

So I can't merge this PR. Sooner or later someone gets problems with emojis or foreign characters.

**Pull request closed without merging**
