### PR TITLE
Introduce stopOnCtrlC in application.

### PR DESCRIPTION
**Pull request by gizahNL**
This allows consuming applications signal that they intend to keep running when control+c is pressed, and instead want the event to be handled by their primitives.

My use case is for a window in which I run shell commands; And that I want to cancel via pressing control+c. The current default of stopping on control+c is kept so there should not be any surprises for anyone updating.

### CODE REVIEW

**Comment by rivo** [comment]
This is what [`Application.SetInputCapture()`](https://pkg.go.dev/github.com/rivo/tview#Application.SetInputCapture) is for. This specific use case is actually documented there. You can also use it to bind "Close Application" to a different key.

**Comment by gizahNL** [comment]
> This is what [`Application.SetInputCapture()`](https://pkg.go.dev/github.com/rivo/tview#Application.SetInputCapture) is for. This specific use case is actually documented there. You can also use it to bind "Close Application" to a different key.

Can you perchance explain how to do it that way? I am able to block handling of control+c that way completely, but I don't see a way to let control+c be passed down chain without the application getting stopped.

**Comment by rivo** [comment]
Actually, your question made me realize that there was indeed no way to forward Ctrl-C to primites. You were able to block it or translate it but not forward.

I fixed this now. There is now a specific way to achieve this. Check out the link above for details.

**Comment by gizahNL** [comment]
> Actually, your question made me realize that there was indeed no way to forward Ctrl-C to primites. You were able to block it or translate it but not forward.
> 
> I fixed this now. There is now a specific way to achieve this. Check out the link above for details.

Many thanks! That will work for me !

**Pull request closed without merging**
