### PR TITLE
Fix for GetFormItemByLabel Issue

### PR DESCRIPTION
**Pull request by joegrasse**
Fix for issue I encountered on https://github.com/rivo/tview/issues/94.

### CODE REVIEW

**Comment by rivo** [comment]
I opted for a slightly different solution here. Instead of adding padding to the label, one can set a label width. The label text does not get modified anymore. This should make the `GetFormItemByLabel()` work.

**Comment by joegrasse** [comment]
I just thought I would note that your change does cause a backwards incompatibility.

**Comment by rivo** [comment]
Where does it? I think I'm not seeing it...

**Comment by rivo** [comment]
`SetFormAttribrutes()` is meant to be used only by the `Form` class. I guess I could have made it private in the first place.

**Comment by joegrasse** [comment]
Your latest changes work for me. Thank you.

**Pull request closed without merging**
