### PR TITLE
Add option to highlight entire selected row of a List item

### PR DESCRIPTION
**Pull request by ardnew**
This implements the option requested in #219

### CODE REVIEW

**Comment by rivo** [comment]
Generally ok with this. But could you please rename the member variable (and the function accordingly) to `highlightTextOnly`? I find `spanSelectedBackgroundColor` confusing.

GitHub says there are merge conflicts. You might want to pull in the latest changes before resubmitting.

**Comment by rivo** [comment]
You know, I've been thinking about this some more and I think this should not be the default. It will look quite odd on very wide screens with little text on a line.

So I think this should be called `highlightFullLine` instead and one can then use `SetHighlightFullLine(true)` to activate it.

**Comment by rivo** [comment]
Do you still want to make the proposed change? (It seems that you'll need to resolve a merge conflict, too, as the file has changed in the meantime.)

**Comment by ardnew** [comment]
finally resolved conflict and updated the field name as requested, please pull when ready

**Comment by ardnew** [comment]
> You know, I've been thinking about this some more and I think this should not be the default. It will look quite odd on very wide screens with little text on a line.

Yeah, I suppose in that case it might look odd. Is that really the most common case though?

To me it seems like the current implementation diverges from widespread convention. I can't think of any list in any application where only the text is highlighted (all context menus, dropdown menus, list boxes, combo boxes in macOS, Windows, Gnome, and KDE; all list controls in Chrome and Firefox). 

I realize these are graphical applications, but why would the convention be any different?

**Comment by rivo** [comment]
I don't know. I just tried it on `demos/list/main.go` and it looks odd to me. And I don't even have a huge screen (working on a 13 inch laptop).

But if there are actual complaints from more users, I'm willing to rethink this.

**Pull request merged**
