### PR TITLE
Optimizations for TextView

### LINKED ISSUE #266: TextView consumes too much CPU during reindexing/drawing
I've noticed that a simple textview, without colors, regions or wrapping will still consume close to a 100% of a cpu core  when its being written to, if it contains a lot of text. A scenario like that is pretty easily achievable if one tries to tail a busy log file via a textview.  The bulk of that time is taken by the stringWidth function, either through the decomposeString, later on when calculating the line width for the index itself, and finally during iterateString.

An extremely naive fix was to add a simple map as a cache to the stringWidth util function. This removed the entire bottleneck on subsequent scrolls

### PR DESCRIPTION
**Pull request by urandom**
Only clear the index when the textview dimensions change or the text
itself is cleared.
Add to the index when new text is added to the view.

Fixes #266

### CODE REVIEW

**Comment by tslocum** [comment]
When comparing benchmarks the fol

**Comment by tslocum** [comment]
I've created benchmarks for writing to and drawing TextViews (submitted as #356) and compared the results before and after applying these optimizations.

---

`go test -run=NONE -bench=. -count=3`

[Before](https://paste.sr.ht/%7Etslocum/97a85e91a875a4038364b4c2c757cd40d67388c4#before-applying-textview-optimizations)

[After](https://paste.sr.ht/%7Etslocum/97a85e91a875a4038364b4c2c757cd40d67388c4#after-applying-textview-optimizations)

---

`benchcmp -best -changed`

[Comparison](https://paste.sr.ht/%7Etslocum/97a85e91a875a4038364b4c2c757cd40d67388c4#comparison-of-textview-optimizations)

**Comment by Bios-Marcel** [comment]
So, it has gotten worse? Because `after` shows more ns/operation and such

**Comment by tslocum** [comment]
Based on the benchmark results, these optimizations:

* Increase the amount of time it takes to write to unwrapped TextViews by 350%
* Do not affect the amount of time it takes to write to wrapped TextViews
* Increase the number of allocations when writing to both unwrapped and wrapped TextViews by 1000%
* Increase the allocation size when writing to unwrapped TextViews by 500%
* Do not affect the allocation size of writing to wrapped TextViews
* Reduce the amount of time it takes to draw unwrapped TextViews by 65%
* Reduce the amount of time it takes to draw wrapped TextViews by 20%
* Reduce the allocation size when drawing unwrapped TextViews by 40%
* Reduce the allocation size when drawing wrapped TextViews by 20%

**Comment by urandom** [comment]
This change optimizes for large amounts of text, especially one that constantly gets appended to (displaying a tailing log). 
Your benchmarks present a static text of 512 bytes, where performance is quite insignificant.

**Comment by tslocum** [comment]
Thanks for your feedback.  I've updated the tests and benchmarks to include cases where a small amount of data is written to a TextView that contains a lot of data.  You can see these changes in the updated pull request I linked earlier.

[Updated results and comparison](https://paste.sr.ht/%7Etslocum/e1d3c7e14637a6e3ff7429dc15b33bfa40fcae4d#comparison-of-textview-optimizations-updated)

**Comment by foxcpp** [comment]
Any chance to have this merged? I am currently using tview for TUI for my experimental chat application and use TextView as a chat log.

**Comment by foxcpp** [comment]
@tslocum, hey, since you are maintaining cview, what do you think about getting that PR in? Imo this is a good improvement. I would submit it but there are some non-trivial conflicts so I am not sure about them.

**Comment by foxcpp** [comment]
I rebased it here: https://github.com/foxcpp/tview/tree/textview-opts but as I said, I am not sure if I did everything correctly.
Also included my small optimization from #435.

**Comment by tslocum** [comment]
Thanks @foxcpp.  I am interested in merging your changes into [cview](https://gitlab.com/tslocum/cview).  I'll let you know once I've had a chance to review your changes.

**Comment by tslocum** [comment]
Hey @foxcpp, I only see your optimization to use TrimRightFunc in your updated branches.  Were you able to review the benchmark results which seem to show these changes cause decreases in performance?

**Comment by foxcpp** [comment]
@tslocum Woops, forgot to `git push`. Now it should be there. Also added your benchmarks.

Here is the benchcmp output master vs textview-opts branch: [benchcmp.txt](https://github.com/rivo/tview/files/4537621/benchcmp.txt)

**Comment by tslocum** [comment]
I believe you have the results backwards: when not wrapping text, Draw is improved 60% while Write is up to 600% slower (if old is master and new is textview-opts).

**Comment by foxcpp** [comment]
Woops x2. You are right.

**Comment by rivo** [comment]
Closing this as it's obsolete. Check out the new `TextView` implementation for details.

**Pull request closed without merging**
