### PR TITLE
Allow left and right movement within inputfield

### PR DESCRIPTION
**Pull request by Asa-Dawson**
I've patched inputfield.go to allow left and right movement and editing the input's text from the cursor's position. This is my first patch for this codebase so I'm sure it's not up to scratch but I'm 100% happy to make changes and resubmit.

### CODE REVIEW

**Comment by rivo** [comment]
Thanks. I really appreciate your effort. Unfortunately, the changes this needs to make it mergeable are significant. Apart from a few small things, the main issue is that you can't assume the `InputField`'s text to be just one-cell-width characters represented by one byte. In other words, things like `len(i.text)` or `i.text[i.cursor:]` don't work with lots of Unicode characters which (A) will often consist of multiple bytes and even multiple runes and (B) don't always have a width of one screen cell. See #9, #101, and #161 for examples.

I'm guessing that making it work properly with Unicode characters will require you to rewrite almost the whole thing so I'm not sure it's worth it.

I was about to start to work on this myself now anyway. But if I do it, it would mean closing your pull request, i.e. not merging it. So I'd like to hear your thoughts on that first.

**Comment by Asa-Dawson** [comment]
I've been dogfooding with this merge locally and I've recognised the issues you're talking about alongside a bug involving the field width causing wrapping bugs. 

Is there a consistent way to split up the input field's text into 1-cell-wide character collections? if so I'm happy to work on porting this from the naive one-byte approach if you're happy for me to continue doing that.

Otherwise if you have a better/preferred method or want to work on it yourself I'm totally happy for you to close this without merging, I'm not concerned about my contribution particularly I just want to make tview better :)

**Comment by rivo** [comment]
Thanks. Again, I appreciate your contribution, even if I don't end up merging it. (Do not let this discourage you.)

Some characters are more than one cell wide. (Lots of Chinese characters are.) Some are modifiers which are 0 cells wide but must be combined with other characters. Then there are combinations of them (see "zero-width joiners"). It took me a whole bunch of issues to figure it all out. All of these must be considered.

As mentioned, I'm starting work on this now anyway. So I don't think you need to start a complete rewrite of your PR (which I have a feeling it would be).

I'm keeping this open until the whole thing is resolved. I might be able to give you more feedback in general once I've dug into this issue.

**Comment by rivo** [comment]
My latest commit closes your PR. I hope this is ok for you. This was a major effort, much less simple than I thought. I've given some more details here: https://github.com/rivo/tview/issues/103#issuecomment-430894330

Thanks again for your contribution. Actually, your PR was what finally triggered me to tackle this issue.

**Comment by Asa-Dawson** [comment]
Closing the PR is fine by me, I'm very happy to see tview improving! 🎈

Thanks for your hard work!

**Pull request closed without merging**
